default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: authentication_rails_7_example_development

test:
  <<: *default
  database: authentication_rails_7_example_test

production:
  <<: *default
  database: authentication_rails_7_example_production
  username: authentication_rails_7_example
  password: <%= ENV["AUTHENTICATION_RAILS_7_EXAMPLE_DATABASE_PASSWORD"] %>
