# this is a basic workflow that is manually triggered

name: Bump version

# Controls when the action will run. Workflow runs when manuall trigged using the UI
# or API
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be show in the UI instead of 'name'
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

# A workflow run is made up of one or more jobs that can run sequentially or in paralle
jobs:
  # This workflow contains a single job called "bump-version"
  bump-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Check out the content (source branch). Use a dpeloy key so that
    # When whe push changes, it will trigger the release workflow
    # run that runs on: tag. (Using the GitHub token would
    # not run the workflow to prevent infinite recursion.)
    - name: Check out source
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true

    - name: Install dependencies
      env:
        RAILS_ENV: test
      run: |
        bundle install
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3


       
        
      
    
    
        
        
