name: Create Release
on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  create-github-release:
    name: Create GitHubRelease
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          key: ${{ secrets.GH_TOKEN }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Create release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN }}
      
    
